export APPLAUNCHER_DIR=/flywheel/v0/converters/slicer/slicer/bin

PATH=$APPLAUNCHER_DIR
PATH=$APPLAUNCHER_DIR/..bin:$PATH
PATH=$APPLAUNCHER_DIR/../lib/Slicer-4.11:$PATH
PATH=$APPLAUNCHER_DIR/../lib/Python/lib:$PATH

PYTHONPATH=$APPLAUNCHER_DIR/../lib/Slicer-4.11
PYTHONPATH=$APPLAUNCHER_DIR/../lib/Slicer-4.11/qt-scripted-modules:$PYTHONPATH
PYTHONPATH=$APPLAUNCHER_DIR/../lib/Slicer-4.11/qt-loadable-modules:$PYTHONPATH
PYTHONPATH=$APPLAUNCHER_DIR/../lib/vtkTeem:$PYTHONPATH
PYTHONPATH=$APPLAUNCHER_DIR/../bin/Python:$PYTHONPATH
PYTHONPATH=$APPLAUNCHER_DIR/../lib/Slicer-4.11/qt-loadable-modules/Python:$PYTHONPATH
PYTHONPATH=$APPLAUNCHER_DIR/../lib/Python/lib/python3.6:$PYTHONPATH
PYTHONPATH=$APPLAUNCHER_DIR/../lib/Python/lib/python3.6/lib-dynload:$PYTHONPATH
PYTHONPATH=$APPLAUNCHER_DIR/../lib/Python/lib/python3.6/site-packages:$PYTHONPATH

PYTHONHOME=$APPLAUNCHER_DIR/../lib/Python
PYTHONNOUSERSITE=1
PIP_REQUIRE_VIRTUALENV=0
SSL_CERT_FILE=$APPLAUNCHER_DIR/../share/Slicer-4.11/Slicer.crt

export PATH
export PYTHONPATH
export PYTHONHOME
export PYTHONNOUSERSITE
export PIP_REQUIRE_VIRTUALENV
export SSL_CERT_FILE